export const REQUEST_USERS_LIST_SUCCESS = 'REQUEST_USERS_LIST_SUCCESS';
export const REQUEST_USERS_LIST_FAIL = 'REQUEST_USERS_LIST_FAIL';

export const REQUEST_USER_CREATE_SUCCESS = 'REQUEST_USER_CREATE_SUCCESS';
export const REQUEST_USER_CREATE_FAIL = 'REQUEST_USER_CREATE_FAIL';

export const REQUEST_USER_SEARCH_SUCCESS = 'REQUEST_USER_SEARCH_SUCCESS';
export const REQUEST_USER_SEARCH_FAIL = 'REQUEST_USER_SEARCH_FAIL';

export const REQUEST_USER_DELETE_SUCCESS = 'REQUEST_USER_DELETE_SUCCESS';
export const REQUEST_USER_DELETE_FAIL = 'REQUEST_USER_DELETE_FAIL';

export const REQUEST_USER_EDIT_SUCCESS = 'REQUEST_USER_EDIT_SUCCESS';
export const REQUEST_USER_EDIT_FAIL = 'REQUEST_USER_EDIT_FAIL';

export const SHOW_ADD_NEW = 'SHOW_ADD_NEW';
export const HIDE_ADD_NEW = 'HIDE_ADD_NEW';
export const SHOW_SEARCH = 'SHOW_SEARCH';
export const HIDE_SEARCH = 'HIDE_SEARCH';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
