export const REQUEST_USERS_LIST_SUCCESS = 'REQUEST_USERS_LIST_SUCCESS';
export const REQUEST_USERS_LIST_FAIL = 'REQUEST_USERS_LIST_FAIL';

export const REQUEST_USER_CREATE_SUCCESS = 'REQUEST_USER_CREATE_SUCCESS';
export const REQUEST_USER_CREATE_FAIL = 'REQUEST_USER_CREATE_FAIL';

export const REQUEST_USER_SEARCH_SUCCESS = 'REQUEST_USER_SEARCH_SUCCESS';
export const REQUEST_USER_SEARCH_FAIL = 'REQUEST_USER_SEARCH_FAIL';

